name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    # Run unit tests, upload code coverage, and publish documentation
    name: Test, Upload Code Coverage, and Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Sphinx Documents
        env:
          HEAD_REF: ${{ github.head_ref }} 
          REF_NAME: ${{ github.ref_name }} 
        run: |
          slugify () {
            echo "$1" | iconv -t ascii//TRANSLIT | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z
          }

          echo $(slugify "$HEAD_REF")
          echo $(slugify "$REF_NAME")